package main

#Tool: {
	name:             string
	title:            string | *name
	description:      string
	inputSchemaName:  or(#SchemaNameArray) | error("\(inputSchemaName) does not exist")
	outputSchemaName: or(#SchemaNameArray) | error("\(outputSchemaName) does not exist")
}

#Tools: [N=string]: #Tool & {
	name: N
}

#RustToolHeader: """
	// This file is generated by cue
	// it lists all Tools that are listed in the Tools attribute
	// this is used in lib.rs
	use crate::bindings::wasmcp::mcp_v20251125::mcp::{Tool, ToolOptions};
	use once_cell::sync::Lazy;

	pub static TOOLS: Lazy<Vec<Tool>> = Lazy::new(|| vec![
	"""

#RustToolFooter: """
	]);
	"""

#ToolToRustTool: {
	inputTool:   #Tool
	inputSchema: string
	outputRust:  string &
		"""
            Tool {
                name: "\(inputTool.name)".to_string(),
                input_schema: r###"\(inputSchema)"###.to_string(),
                options: Some(ToolOptions {
                    meta: None,
                    icons: None,
                    annotations: None,
                    description: Some("\(inputTool.description)".to_string()),
                    output_schema: None,
                    title: Some("\(inputTool.title)".to_string()),
                }),
            },
            """
}

#RustToolCallTemplate: {
	inputTool:  #Tool
	outputRust: """
	        "\(inputTool.name)" => implementation::ToolImplementation::\(inputTool.name)(request),
	"""
}

#RustToolCallHeader: """
	// this file is generated by cue
	// it generates the the tool function calls used in lib.rs
	use crate::{
	    bindings::wasmcp::mcp_v20251125::{
	        mcp::{CallToolRequest, CallToolResult},
	        server_handler::ErrorCode,
	    },
	    implementation,
	};

	pub trait Tools {
	"""

#RustToolCallTraitTemplate: {
	inputTool:  #Tool
	outputRust: """
	fn \(inputTool.name)(request: CallToolRequest) -> Result<Option<CallToolResult>, ErrorCode>;
	"""
}

#RustToolCallTraitInlay: """
	}

	pub fn tool_calls(request: CallToolRequest) -> Result<Option<CallToolResult>, ErrorCode> {
	    match request.name.as_str() {
	"""

#RustToolCallFooter: """
	        _ => Ok(None), // We don't handle this tool
	    }
	}
	"""

SchemaNames: {for k, _ in Schemas {"\(k)": "\(k)"}}
#SchemaNameArray: [for k, _ in Schemas {k}]

//Schemas: #Schemas
Tools: #Tools

#TestInput: {
	// The name of the person to greet
	name: string
	// The type of pet of the person
	pet: "dog" | "cat"
}

#TestOutput: {
	message: string
}

Schemas: {
	TestInput:  #TestInput
	TestOutput: #TestOutput
}

Tools: #Tools & {
	"greeter": {
		description:      "Greets somebody"
		inputSchemaName:  SchemaNames.TestInput
		outputSchemaName: SchemaNames.TestOutput
	}
}
