package main

#Tool: {
	name:             string
	title:            string | *name
	description:      string
	inputSchema:      #Schema
	outputSchema:     #Schema
	inputSchemaName:  inputSchema._$name
	outputSchemaName: outputSchema._$name
}

#Tools: [N=string]: #Tool & {
	name: N
}

#RustToolHeader: """
	// This file is generated by cue
	// it lists all Tools that are listed in the Tools attribute
	use crate::bindings::wasmcp::mcp_v20251125::mcp::{Tool, ToolOptions};
	use once_cell::sync::Lazy;

	pub static TOOLS: Lazy<Vec<Tool>> = Lazy::new(|| vec![
	"""

#RustToolFooter: """
	]);
	"""

#ToolToRustTool: {
	inputTool:   #Tool
	inputSchema: string
	outputRust:  string &
		"""
            Tool {
                name: "\(inputTool.name)".to_string(),
                input_schema: r###"\(inputSchema)"###.to_string(),
                options: Some(ToolOptions {
                    meta: None,
                    icons: None,
                    annotations: None,
                    description: Some("\(inputTool.description)".to_string()),
                    output_schema: None,
                    title: Some("\(inputTool.title)".to_string()),
                }),
            },
            """
}

#RustToolCallTemplate: {
	inputTool:  #Tool
	outputRust: """
	        "\(inputTool.name)" => implementation::ToolImplementation::\(inputTool.name)(request),
	"""
}

#RustToolCallHeader: """
	// this file is generated
	// it calls the tool functions
	use crate::{
	    bindings::wasmcp::mcp_v20251125::{
	        mcp::{CallToolRequest, CallToolResult},
	        server_handler::ErrorCode,
	    },
	    implementation,
	};

	pub trait Tools {
	"""

#RustToolCallTraitTemplate: {
	inputTool:  #Tool
	outputRust: """
	fn \(inputTool.name)(request: CallToolRequest) -> Result<Option<CallToolResult>, ErrorCode>;
	"""
}

#RustToolCallTraitInlay: """
	}

	pub fn tool_calls(request: CallToolRequest) -> Result<Option<CallToolResult>, ErrorCode> {
	    match request.name.as_str() {
	"""

#RustToolCallFooter: """
	        _ => Ok(None), // We don't handle this tool
	    }
	}
	"""

#Schema: {
	_$name: string
	...
}

#Schemas: [N=string]: #Schema & {
	_$name: N
}

Schemas: #Schemas
Tools:   #Tools

Schemas: #Schemas & {
	TestInput: {
		name: string
		pet:  "dog" | "cat"
	}
	TestOutput: {
		message: string
	}
}

Tools: #Tools & {
	"greeter": {
		description:  "Greets somebody"
		inputSchema:  Schemas.TestInput
		outputSchema: Schemas.TestOutput
	}
}
