build:
  command: make && wasmcp compose server --runtime wasmcloud ./target/wasm32-wasip2/release/acme_mcp.wasm --force -o ./target/acme_mcp_server.wasm
  component_path: target/acme_mcp_server.wasm

dev:
  components:
    - name: acme-component
      file: target/wasm32-wasip2/release/acme_component.wasm